php simply_addsrc.php http://globalcio.ru/ >> data/1.log 
php simply_addsrc.php http://computerworld.ru/ >> data/1.log 
php simply_addsrc.php http://hardnsoft.ru/ >> data/1.log 
php simply_addsrc.php http://iks-media.ru/ >> data/1.log 
php simply_addsrc.php http://itexpert.ru/ >> data/1.log 
php simply_addsrc.php http://marketelectro.ru/ >> data/1.log 
php simply_addsrc.php http://www.sistema.ru/ >> data/1.log 
php simply_addsrc.php http://www.vestniknews.ru/ >> data/1.log 
php simply_addsrc.php http://www.stud-forum.ru/ >> data/1.log 
php simply_addsrc.php http://www.rudn.ru/?pagec=1
php simply_addsrc.php http://kgeu.ru/ >> data/1.log 
php simply_addsrc.php http://kubstu.ru/ >> data/1.log 
php simply_addsrc.php http://mol-express.com/ >> data/1.log 
php simply_addsrc.php http://www.mpei.ru/ >> data/1.log 
php simply_addsrc.php http://www.new-management.info/ >> data/1.log 
php simply_addsrc.php http://gazeta-ov.ru/ >> data/1.log 
php simply_addsrc.php http://www.openet.ru/ >> data/1.log 
php simply_addsrc.php http://ibk.ru/ >> data/1.log 
php simply_addsrc.php http://www.pressmk.ru/ >> data/1.log 
php simply_addsrc.php http://technicamolodezhi.ru/ >> data/1.log 
php simply_addsrc.php http://ecovestnik.ru/ >> data/1.log 
php simply_addsrc.php http://www.allventure.ru/ >> data/1.log 
php simply_addsrc.php http://ria-stk.ru/ >> data/1.log 
php simply_addsrc.php http://popnano.ru/ >> data/1.log 
php simply_addsrc.php http://www.ini21.ru/ >> data/1.log 
php simply_addsrc.php http://mediatimes.info/ >> data/1.log 
php simply_addsrc.php http://ria-stk.ru/ >> data/1.log 
php simply_addsrc.php http://www.portalnano.ru/ >> data/1.log 
php simply_addsrc.php http://www.hij.ru/ >> data/1.log 
php simply_addsrc.php http://ria-stk.ru/ >> data/1.log 
php simply_addsrc.php http://ria-stk.ru/ >> data/1.log 
php simply_addsrc.php http://wwwinfo.jinr.ru/jinrmag/ >> data/1.log 
php simply_addsrc.php http://9000innovations.ru/ >> data/1.log 
php simply_addsrc.php http://ogjrussia.com/ >> data/1.log 
php simply_addsrc.php http://portal-energo.ru/ >> data/1.log 
php simply_addsrc.php http://proektant.ru/ >> data/1.log 
php simply_addsrc.php http://Prom-industry.ru/ >> data/1.log 
php simply_addsrc.php http://www.au92.ru/ >> data/1.log 
php simply_addsrc.php http://avite.ru/ >> data/1.log 
php simply_addsrc.php http://energoacademy.ru/ >> data/1.log 
php simply_addsrc.php http://vestnikao.ru/ >> data/1.log 
php simply_addsrc.php http://gazeta-vid.ru/ >> data/1.log 
php simply_addsrc.php http://npngs.ru/ >> data/1.log 
php simply_addsrc.php http://EnginRussia.ru/ >> data/1.log 
php simply_addsrc.php http://tatneft.ru/ >> data/1.log 
php simply_addsrc.php http://elcomdesign.ru/ >> data/1.log 
php simply_addsrc.php http://www.gd.ru/ >> data/1.log 
php simply_addsrc.php http://hbr-russia.ru/ >> data/1.log 
php simply_addsrc.php http://hbr-russia.ru/ >> data/1.log 
php simply_addsrc.php http://www.m3m.ru/ >> data/1.log 
php simply_addsrc.php http://www.ru.mdz-moskau.eu/ >> data/1.log 
php simply_addsrc.php http://rsnews.net/ >> data/1.log 
php simply_addsrc.php http://www.sistema.ru/ >> data/1.log 
php simply_addsrc.php http://www.rodgaz.ru/ >> data/1.log 
php simply_addsrc.php http://www.sf-online.ru/ >> data/1.log